### ISSUE TITLE
Error: Cannot find module 'is-there'

### ISSUE THREAD

**Issue by RWOverdijk** [IonicaBizau/image-to-ascii-cli#3]
```
nodejs[ image-to-ascii -i ~/Desktop/Screen\ Shot\ 2015-03-19\ at\ 14.40.19.png                                                                                                                          feature/language * ] 10:38 PM
module.js:339
    throw err;
    ^

Error: Cannot find module 'is-there'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/rwoverdijk/.nvm/versions/node/v4.2.1/lib/node_modules/image-to-ascii-cli/bin/image-to-ascii:9:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

**Comment by IonicaBizau** [comment]
Whoups, fixed! The `is-there` dependency was missing from `package.json`. Should be fixed now in the patch release. :rocket:

**Comment by RWOverdijk** [comment]
Thanks! :)
